spring:
  application:
    name: imwa
  messages:
    basename: messages
  datasource:
    url: jdbc:h2:file:./data/imwa-db
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
  sql:
    init:
      mode: embedded
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
